config/routes.rb
Rails.application.routes.draw do
  
  resources :billboards
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  get 'songs/search', to: 'songs#search'

  get 'welcome/about', to: 'welcome#about', :as => :about

  resources :users do
    resources :playlists do
      resources :songs
    end
  end  

  resources :billboards, only: [:show, :index] do
    resources :playlists do
      resources :songs
    end
  end  

  root to: 'welcome#index'

  get  '/login', :to => 'sessions#new', :as => :login
  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get "/signout" => "sessions#destroy", :as => :signout

  get '/users/:user_id/playlists/:id/spotify' => 'playlists#spotify', :as => :spotify

end

app/models/billboard.rb
class Billboard < ActiveRecord::Base
end

app/models/billboard_scraper.rb
class BillboardScraper
  require 'open-uri'
  require 'nokogiri'

  def get_top_songs
    html = open("http://www.billboard.com/charts/hot-100").read
    doc = Nokogiri::HTML(html)
    spotify_ids = doc.search(".spotify").collect {|song| song.attributes["href"].value.gsub("https://embed.spotify.com/?uri=spotify:track:","")}

    SpotifyWrapper.new(spotify_ids).create_song_objects
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :songs
  belongs_to :user
end

app/models/song.rb
class Song < ActiveRecord::Base

  require 'json'
  require 'open-uri'

  belongs_to :playlist
  delegate :user, to: :playlist

  def assign_bpm
    bpm = EchonestWrapper.new.find_bpm(self)
    self.bpm = bpm
    self.save
  end

  def sort_to_playlist(user)
    if self.bpm < 70 
      self.playlist = Playlist.find_by(:name => "Sleep", :user_id => user.id)
    elsif self.bpm >= 70 && self.bpm < 90
      self.playlist = Playlist.find_by(:name => "Study", :user_id => user.id)
    elsif self.bpm >= 90 && self.bpm < 120  
      self.playlist = Playlist.find_by(:name => "Party", :user_id => user.id)
    else 
      self.playlist = Playlist.find_by(:name => "Workout", :user_id => user.id)
    end
    self.save
  end

end

app/models/song_sorter.rb
require 'json'
require 'open-uri'

class SongSorter

  def initialize
    @echonest_api = ENV["echonest_api_key"]
  end

  def get_spotify_json
    JSON.load(open "http://charts.spotify.com/api/tracks/most_streamed/us/weekly/latest")
  end

  def get_song_objects(hash)
    hash["tracks"][1..100].each do |song_hash|
      Song.find_or_create_by(:title => song_hash['track_name'], :artist => song_hash['artist_name'], :track_url => song_hash['track_url'].gsub("https://play.spotify.com/track/", ""))
    end
  end
  
  def get_echonest_url(track_url)
    "http://developer.echonest.com/api/v4/song/profile?api_key=#{@echonest_api}&track_id=spotify:track:#{track_url}&bucket=id:spotify&bucket=audio_summary" 
  end

  def assign_bpms
    Song.all.each do |song|
      json_link = get_echonest_url(song.track_url)
      hash = JSON.load(open "#{json_link}")
      song.bpm = hash["response"]["songs"][0]["audio_summary"]["tempo"]
      song.save
    end
  end

  def define_categories
    categories = [Category.find_or_create_by(:name => "Sleep"), Category.find_or_create_by(:name => "Study"), Category.find_or_create_by(:name => "Party"), Category.find_or_create_by(:name => "Workout")]
  end

  def sort_into_category
    Song.all.each do |song|
      if song.bpm < 70 
        song.category = Category.find_by(:name => "Sleep")
        song.save
      elsif song.bpm >= 70 && song.bpm < 90
        song.category = Category.find_by(:name => "Study")
        song.save
      elsif song.bpm >= 90 && song.bpm < 120  
        song.category = Category.find_by(:name => "Party")
        song.save
      else 
        song.category = Category.find_by(:name => "Workout")
        song.save
      end
    end
  end

  def self.sort
    self.new.call
  end

  def call 
    define_categories
    spotify_hash = get_spotify_json
    get_song_objects(spotify_hash)
    assign_bpms
    sort_into_category
  end 

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :playlists
  has_many :songs, through: :playlists

  validates :name, :presence => true

  def give_playlists
    Playlist.find_or_create_by(:name => "Sleep", :user_id => self.id)
    Playlist.find_or_create_by(:name => "Study", :user_id => self.id)
    Playlist.find_or_create_by(:name => "Party", :user_id => self.id)
    Playlist.find_or_create_by(:name => "Workout", :user_id => self.id)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["display_name"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  helper_method :current_user, :login_required, :logged_in?, :billboard_user
   
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def login_required
    if !logged_in?
      redirect_to root_path, :notice => "You need to login"
    end
  end

  def logged_in?
    !!current_user
  end 

  def billboard_user
    User.find_by(:name => "Billboard Hot 100")
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController

  def index
    @billboard = billboard_user
    @playlists = @billboard.playlists
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index 
    @user = current_user
    @playlists = @user.playlists
  end
  
  def show
    @playlist = Playlist.find(params[:id])
    if params[:user_id]
      @user = User.find(params[:user_id])
    else
      @user = billboard_user
    end
  end 

  def spotify
    @playlist = Playlist.find(params[:id])
    SpotifyWrapper.new.add_playlist_to_spotify(@playlist)
    redirect_to user_playlist_path(current_user, @playlist)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  require 'rspotify'

  def new
  end

  def create    
    auth = request.env["omniauth.auth"]     
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)   
    session[:user_id] = user.id     
    redirect_to root_url, :notice => "Signed in!"
    user.give_playlists
    $spotify_user = RSpotify::User.new(auth)
  end

  def failure
    render :text => "Sorry, but you didn't allow access to our app!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index 
    @playlists = Playlist.all
  end

  def show 
    @song = Song.find(params[:id])
  end

  def search
    @song = Song.new
    @user = current_user
    @playlist = @user.playlists.first
    if !params[:query].empty?
      @songs = (SpotifyWrapper.new.search_for_song(params["query"]))[0..14]
      @search = params["query"]
    else
      redirect_to songs_search_path
    end
  end

  def create
    @song = SpotifyWrapper.new.create_song_objects(song_params["track_url"])
    @song.save
    @song.assign_bpm
    @song.sort_to_playlist(current_user)
    @playlist = @song.playlist
    redirect_to user_playlist_path(current_user, @playlist)
  end

  private
    def song_params
      params.require(:song).permit(:title, :artist, :track_url, :bpm, :genre, :playlist_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
  end

  def show
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/billboards/index.html.erb
<div align ="center">

<h2>Pick a category for a curated playlist based on Billboard's Hot 100</h2>
<br>

<div class="main-photo" id="sleep">
<%= link_to image_tag("sleep.jpg", :border => 0), user_playlist_path(@billboard, @playlists.find_by(:name => "Sleep")) %>
</div>

<div class="main-photo" id="study">
<%= link_to image_tag("study.jpg", :border => 0), user_playlist_path(@billboard, @playlists.find_by(:name => "Study")) %>
</div>

<div class="main-photo" id="party">
<%= link_to image_tag("party.jpg", :border => 0), user_playlist_path(@billboard, @playlists.find_by(:name => "Party")) %>
</div>

<div class="main-photo" id="workout">
<%= link_to image_tag("workout.jpg", :border => 0), user_playlist_path(@billboard, @playlists.find_by(:name => "Workout")) %>
</div>

</div>

app/views/categories/show.html.erb
<div align ="center">

<h1><%= @category.name %> Playlist</h1>

<% @category.songs.each do |song| %>

<h3><%= link_to "#{song.title} (#{song.artist})", "/songs/#{song.id}" %></h3>

<iframe src="https://embed.spotify.com/?uri=spotify:track:<%= song.track_url %>" width="300" height="80" frameborder="0" allowtransparency="true"></iframe>

<br>
<br>

<% end %>

</div>

app/views/playlists/_playlists.html.erb
<div class="main-photo" id="sleep">
<%= link_to image_tag("sleep.jpg", :border => 0), user_playlist_path(@user, @playlists.find_by(:name => "Sleep")) %>
</div>

<div class="main-photo" id="study">
<%= link_to image_tag("study.jpg", :border => 0), user_playlist_path(@user, @playlists.find_by(:name => "Study")) %>
</div>

<div class="main-photo" id="party">
<%= link_to image_tag("party.jpg", :border => 0), user_playlist_path(@user, @playlists.find_by(:name => "Party")) %>
</div>

<div class="main-photo" id="workout">
<%= link_to image_tag("workout.jpg", :border => 0), user_playlist_path(@user, @playlists.find_by(:name => "Workout")) %>
</div>

app/views/playlists/_song_search.html.erb
<h3>Add a song to be sorted!</h3>

<%= form_tag songs_search_path, method: "get" do |f| %>

<div class="form-group">
  <div class="input-group row col-sm-4">

    <%= text_field_tag(:query, "", placeholder: "enter a song", class: "form-control") %>
    <span class="input-group-btn"><%= submit_tag "Search", class: "btn btn-default" %></span>
  </div>
</div>

<% end %>

app/views/playlists/index.html.erb
<div align ="center">

<h2><%= @user.name %>'s Playlists</h2>
<br>

<%= render 'song_search' %>

<%= render 'playlists' %>

</div>

app/views/playlists/show.html.erb
<div align ="center">

<h1><%= @playlist.name %> Playlist</h1>

<% @playlist.songs.each do |song| %>

<h3><%= link_to "#{song.title} (#{song.artist})", user_playlist_song_path(@user, @playlist, song) %></h3>

<iframe src="https://embed.spotify.com/?uri=spotify:track:<%= song.track_url %>" width="300" height="80" frameborder="0" allowtransparency="true"></iframe>

<br>
<br>

<% end %>

<h4><%= link_to "Add playlist to my Spotify account", spotify_path %></h4>

</div>

app/views/songs/index.html.erb
<% Song.all.each do |song| %>
Song: <%= song.title %>
<br>
<% end %>

app/views/songs/search.html.erb
<div align ="center" class="container">
<h2>Songs matching "<%= @search %>":</h2>
<br>
<br>
<ul>
<% @songs.each do |song| %>
  <%= song.name %> by <%= song.artists.first.name %>
  <%= form_for [@user, @playlist, @song], as: :song do |f| %>
    <%= f.hidden_field :track_url, :value => song.id %>
    <br>
    <%= f.submit "Add song!", class: "btn btn-primary" %>
  <% end %>
  <br>
  <br>
<% end %>
</ul>
</div>

app/views/songs/show.html.erb
<div align ="center" class="container">

<h1><%= @song.title %></h1>
<h2>By <%= @song.artist %></h2>

</div>

app/views/welcome/about.html.erb
<div align ="center" class="container">



<h3>About the developer</h3>

  <p>Thanks for using Tempo! My name is <a href="http://elainapolson.com/" target="_blank">Elaina Polson</a>, and I am currently a web development student at <a href="http://flatironschool.com/" target="_blank">the Flatiron School</a>. If you have any questions or suggestions regarding this application, please feel free to <a href="mailto:elainapolson@gmail.com?Subject=Hi%20there!" target="_top">reach out to me</a>. In the meantime, you can find me on <a href="https://github.com/elainapolson" target="_blank">Github</a>, <a href="https://www.linkedin.com/in/elainapolson" target="_blank">LinkedIn</a>, <a href="https://twitter.com/elainapolson" target="_blank">Twitter</a>, and <a href="https://instagram.com/elainapolson" target="_blank">Instagram</a>.</p>

 

<h3>Technical Details</h3>

  <p>Tempo is a Rails application that curates playlists based on a user's current activity. Here's how I built it:</p>


  <p>Harnessed Nokogiri to parse through Billboard.com’s Hot 100 list and collect Spotify track identification numbers</li>

  <p>Used Spotify API to find songs by track identification numbers scraped from Billboard</p>

  <p>Utilized Echo Nest API to find a song's beats per minute; filtered songs into categories based on this data</p>

  <p>Integrated OmniAuth to login users via Spotify</p>


</div>

app/views/welcome/index.html.erb
<div align ="center" class="container">

<br>
<br>

<h1>Welcome to tempo, the application that sorts your favorite songs into playlists based on their energy level... So you always have the right playlist for any activity.</h1>
<br>
  <h3>Get started!</h3>

<br>
<%= link_to "Use playlists from Billboard Hot 100", billboards_path, :class => "btn btn-success btn-lg" %>

<% if current_user %>
<%= link_to "Create your own playlists", user_playlists_path(current_user), :class => "btn btn-success btn-lg" %>
<% else %>
<%= link_to "Create your own playlists", "/auth/spotify", :class => "btn btn-success btn-lg" %>
<% end %>

<br>
<br>

</div>