config/routes.rb
Rails.application.routes.draw do
  
  resources :billboards
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  get 'songs/search', to: 'songs#search'

  get 'welcome/about', to: 'welcome#about', :as => :about

  resources :users do
    resources :playlists do
      resources :songs
    end
  end  

  resources :billboards, only: [:show, :index] do
    resources :playlists do
      resources :songs
    end
  end  

  root to: 'welcome#index'

  get  '/login', :to => 'sessions#new', :as => :login
  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get "/signout" => "sessions#destroy", :as => :signout

  get '/users/:user_id/playlists/:id/spotify' => 'playlists#spotify', :as => :spotify

end

app/models/billboard.rb
class Billboard < ActiveRecord::Base
end

app/models/billboard_scraper.rb
class BillboardScraper
  require 'open-uri'
  require 'nokogiri'

  def get_top_songs
    html = open("http://www.billboard.com/charts/hot-100").read
    doc = Nokogiri::HTML(html)
    spotify_ids = doc.search(".spotify").collect {|song| song.attributes["href"].value.gsub("https://embed.spotify.com/?uri=spotify:track:","")}

    SpotifyWrapper.new(spotify_ids).create_song_objects
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :songs
  belongs_to :user
end

app/models/song.rb
class Song < ActiveRecord::Base

  require 'json'
  require 'open-uri'

  belongs_to :playlist
  delegate :user, to: :playlist

  def assign_bpm
    bpm = EchonestWrapper.new.find_bpm(self)
    self.bpm = bpm
    self.save
  end

  def sort_to_playlist(user)
    if self.bpm < 70 
      self.playlist = Playlist.find_by(:name => "Sleep", :user_id => user.id)
    elsif self.bpm >= 70 && self.bpm < 90
      self.playlist = Playlist.find_by(:name => "Study", :user_id => user.id)
    elsif self.bpm >= 90 && self.bpm < 120  
      self.playlist = Playlist.find_by(:name => "Party", :user_id => user.id)
    else 
      self.playlist = Playlist.find_by(:name => "Workout", :user_id => user.id)
    end
    self.save
  end

end

app/models/song_sorter.rb
require 'json'
require 'open-uri'

class SongSorter

  def initialize
    @echonest_api = ENV["echonest_api_key"]
  end

  def get_spotify_json
    JSON.load(open "http://charts.spotify.com/api/tracks/most_streamed/us/weekly/latest")
  end

  def get_song_objects(hash)
    hash["tracks"][1..100].each do |song_hash|
      Song.find_or_create_by(:title => song_hash['track_name'], :artist => song_hash['artist_name'], :track_url => song_hash['track_url'].gsub("https://play.spotify.com/track/", ""))
    end
  end
  
  def get_echonest_url(track_url)
    "http://developer.echonest.com/api/v4/song/profile?api_key=#{@echonest_api}&track_id=spotify:track:#{track_url}&bucket=id:spotify&bucket=audio_summary" 
  end

  def assign_bpms
    Song.all.each do |song|
      json_link = get_echonest_url(song.track_url)
      hash = JSON.load(open "#{json_link}")
      song.bpm = hash["response"]["songs"][0]["audio_summary"]["tempo"]
      song.save
    end
  end

  def define_categories
    categories = [Category.find_or_create_by(:name => "Sleep"), Category.find_or_create_by(:name => "Study"), Category.find_or_create_by(:name => "Party"), Category.find_or_create_by(:name => "Workout")]
  end

  def sort_into_category
    Song.all.each do |song|
      if song.bpm < 70 
        song.category = Category.find_by(:name => "Sleep")
        song.save
      elsif song.bpm >= 70 && song.bpm < 90
        song.category = Category.find_by(:name => "Study")
        song.save
      elsif song.bpm >= 90 && song.bpm < 120  
        song.category = Category.find_by(:name => "Party")
        song.save
      else 
        song.category = Category.find_by(:name => "Workout")
        song.save
      end
    end
  end

  def self.sort
    self.new.call
  end

  def call 
    define_categories
    spotify_hash = get_spotify_json
    get_song_objects(spotify_hash)
    assign_bpms
    sort_into_category
  end 

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :playlists
  has_many :songs, through: :playlists

  validates :name, :presence => true

  def give_playlists
    Playlist.find_or_create_by(:name => "Sleep", :user_id => self.id)
    Playlist.find_or_create_by(:name => "Study", :user_id => self.id)
    Playlist.find_or_create_by(:name => "Party", :user_id => self.id)
    Playlist.find_or_create_by(:name => "Workout", :user_id => self.id)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["display_name"]
    end
  end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController

  def index
    @billboard = billboard_user
    @playlists = @billboard.playlists
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index 
    @user = current_user
    @playlists = @user.playlists
  end
  
  def show
    @playlist = Playlist.find(params[:id])
    if params[:user_id]
      @user = User.find(params[:user_id])
    else
      @user = billboard_user
    end
  end 

  def spotify
    @playlist = Playlist.find(params[:id])
    SpotifyWrapper.new.add_playlist_to_spotify(@playlist)
    redirect_to user_playlist_path(current_user, @playlist)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  require 'rspotify'

  def new
  end

  def create    
    auth = request.env["omniauth.auth"]     
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)   
    session[:user_id] = user.id     
    redirect_to root_url, :notice => "Signed in!"
    user.give_playlists
    $spotify_user = RSpotify::User.new(auth)
  end

  def failure
    render :text => "Sorry, but you didn't allow access to our app!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index 
    @playlists = Playlist.all
  end

  def show 
    @song = Song.find(params[:id])
  end

  def search
    @song = Song.new
    @user = current_user
    @playlist = @user.playlists.first
    if !params[:query].empty?
      @songs = (SpotifyWrapper.new.search_for_song(params["query"]))[0..14]
      @search = params["query"]
    else
      redirect_to songs_search_path
    end
  end

  def create
    @song = SpotifyWrapper.new.create_song_objects(song_params["track_url"])
    @song.save
    @song.assign_bpm
    @song.sort_to_playlist(current_user)
    @playlist = @song.playlist
    redirect_to user_playlist_path(current_user, @playlist)
  end

  private
    def song_params
      params.require(:song).permit(:title, :artist, :track_url, :bpm, :genre, :playlist_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
  end

  def show
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
<p align="center">Made <i class="fa fa-heart"></i> by <a href="https://www.github.com/elainapolson" target="blank">Elaina Polson</a> at <a href="https://www.flatironschool.com" target="blank" style = "text-decoration: none;">Flatiron School</a> | <a href="https://www.github.com/elainapolson/tempo-app" target="blank" style = "text-decoration: none;">Fork the code!</a> </p>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">tempo</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right scrollto">
          <li>
            <%= link_to "Hot 100 Playlists",  billboards_path %>
          </li>
          <li>
            <% if current_user %>
            <%= link_to "My Playlists", user_playlists_path(current_user) %>
            <% end %>
          </li>
          <li>
            <%= link_to "About",  about_path %>
          </li>
          <li>
            <% if current_user %>
            <%= link_to "Log out", signout_path %>
            <% else %>
            <%= link_to "Sign in", "/auth/spotify" %>
            <% end %>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container -->
  </nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Tempo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>




<div class="wrapper">
<%= render 'layouts/navigation' %>
       

<%= yield %>

  <div class="push"></div>
  
</div>


<%= render 'layouts/footer' %>


</body>
</html>